name: Model Component Generator and Updater
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  generate-components:
    name: Generate Components
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Pull changes from remote
        run: git pull origin check
      - name: Build mesheryctl
        run: |
          cd mesheryctl; make;
      - name: Generate Models and Components
        run: |
          cd mesheryctl;
          ./mesheryctl registry generate --spreadsheet-id "11msGGeLX97knVpIPF4WDbz9V4OxqTLuhMFDlzx9ki1E" --spreadsheet-cred "${{ secrets.INTEGRATION_SPREADSHEET_CRED }}"
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generate-logs
          path: ~/.meshery/logs/
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "New Models generated"
          branch: check
      - name: Send Email on Model Generator Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Actions - Workflow Failure
          from: |
            "Model Generator" <shlokmishr08@gmail.com>
          to: prasantmishra2018@gmail.com
          body: |
            The GitHub Actions workflow in ${{ github.repository }} has failed.
            You can find more details in the GitHub Actions log ${{ github.workflow }}.
  check-and-email-registry-generate-error:
    name: Check and Email Error Log
    runs-on: ubuntu-22.04
    needs: generate-components
    steps:
      - name: Download registry-generate-error
        uses: actions/download-artifact@v4
        with:
          name: generate-logs
          path: ./logs/registry
      - name: Check registry-generate-error file
        id: check-registry-generate-error
        run: |
          if [ -s ./logs/registry/Errors ]; then
            echo "Errors is not empty"
            echo "Errors=true" >> $GITHUB_ENV
          else
            echo "Errors is empty"
            echo "Errors=false" >> $GITHUB_ENV
          fi
      - name: Send Email on Error Logs
        if: env.Errors == 'true'
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Model Generator Error Log
          from: |
            "Model Generator" <testworkflow08@gmail.com>
          to: prasantmishra2018@gmail.com
          body: |
            The model generation process encountered errors. Please find the attached error log for details.
          attachments: ./logs/registry/Errors
  update-components:
    name: Update Components
    needs: generate-components
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Pull changes from remote
        run: git pull origin check
      - name: Build mesheryctl
        run: |
          cd mesheryctl; make;
      - name: Run Model Updater
        run: |
          cd mesheryctl;
          ./mesheryctl registry update -i ../server/meshmodel --spreadsheet-id "11msGGeLX97knVpIPF4WDbz9V4OxqTLuhMFDlzx9ki1E"  --spreadsheet-cred "${{ secrets.INTEGRATION_SPREADSHEET_CRED }}"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "Models updated"
          branch: check
      - name: Send Email on Model Updaters Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Actions - Workflow Failure
          from: |
            "Model Updater" <no-reply@meshery.io>
          to: developers@meshery.io
          body: |
            The GitHub Actions workflow in ${{ github.repository }} has failed.
            You can find more details in the GitHub Actions log ${{ github.workflow }}.
